# Generated by Django 5.0.1 on 2024-07-14 18:40

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arriendo',
            fields=[
                ('idPedido', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre ')),
                ('apellido', models.CharField(max_length=20, verbose_name='Apellido ')),
                ('empresa', models.CharField(default='default_empresa', max_length=60, verbose_name='Empresa')),
                ('email', models.EmailField(max_length=254, verbose_name='Email ')),
                ('cantidad', models.IntegerField(blank=True, null=True, verbose_name='Cantidad ')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id_boleta', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.BigIntegerField()),
                ('fechaCompra', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Categoria')),
                ('nombreCategoria', models.CharField(max_length=50, verbose_name='Nombre de Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Id de Producto')),
                ('marca', models.CharField(max_length=20, verbose_name='Marca')),
                ('nombre', models.CharField(max_length=40, verbose_name='Nombre de producto')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes', verbose_name='Imagen')),
                ('precio', models.IntegerField(blank=True, null=True, verbose_name='Precio')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_obras.categoria', verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='detalle_boleta',
            fields=[
                ('id_detalle_boleta', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('subtotal', models.BigIntegerField()),
                ('id_boleta', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app_obras.boleta')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_obras.producto')),
            ],
        ),
    ]
